import { createClient } from '@supabase/supabase-js';
import { Household, HouseholdMember, Wallet, Category, Transaction, SavingsGoal, Loan, RecurringTransfer } from '../types/database';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';

export const supabase = (supabaseUrl && supabaseAnonKey) 
  ? createClient(supabaseUrl, supabaseAnonKey) 
  : null;

// Demo / Seed initial state for local interactive testing (PHP Currency)
export const initialHousehold: Household = {
  id: 'hh-101',
  name: 'SMCLedger Family Household',
  base_currency: 'PHP',
  created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  updated_at: new Date().toISOString(),
};

export const initialMembers: HouseholdMember[] = [
  {
    id: 'member-steve-admin',
    household_id: 'hh-101',
    user_id: 'usr-steve-admin',
    role: 'admin',
    display_name: 'Steve Cantago (Head Admin Parent)',
    email: 'steve.cantago@gmail.com',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'member-parent-2',
    household_id: 'hh-101',
    user_id: 'usr-parent-2',
    role: 'parent_member',
    display_name: 'Sarah Miller (Member Parent/Guardian)',
    email: 'sarah.miller@example.com',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'member-teen-1',
    household_id: 'hh-101',
    user_id: 'usr-teen-1',
    role: 'member',
    display_name: 'Alex Miller (Kid 1 - High School)',
    email: 'alex.miller@example.com',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'member-kid-2',
    household_id: 'hh-101',
    user_id: 'usr-kid-2',
    role: 'member',
    display_name: 'Chloe Miller (Kid 2 - Middle School)',
    email: 'chloe.miller@example.com',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'member-kid-3',
    household_id: 'hh-101',
    user_id: 'usr-kid-3',
    role: 'member',
    display_name: 'Ethan Miller (Kid 3 - Elementary)',
    email: 'ethan.miller@example.com',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
];

export const initialWallets: Wallet[] = [
  {
    id: 'wallet-main-bank',
    household_id: 'hh-101',
    owner_id: 'member-steve-admin',
    name: 'BDO / BPI Checking (Shared Family)',
    wallet_type: 'bank',
    is_shared: true,
    current_balance: 184500.00,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'wallet-bdo-credit-line',
    household_id: 'hh-101',
    owner_id: 'member-steve-admin',
    name: 'BDO Visa Platinum Credit Line',
    wallet_type: 'credit_card',
    is_shared: true,
    credit_limit: 200000.00,
    current_balance: 34500.00, // Used balance
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'wallet-bpi-credit-line',
    household_id: 'hh-101',
    owner_id: 'member-parent-2',
    name: 'BPI Gold Mastercard Credit Line',
    wallet_type: 'credit_card',
    is_shared: true,
    credit_limit: 150000.00,
    current_balance: 18200.00, // Used balance
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'wallet-savings-bank',
    household_id: 'hh-101',
    owner_id: 'member-steve-admin',
    name: 'High-Yield Reserve & Tuition Sinking Fund',
    wallet_type: 'bank',
    is_shared: true,
    current_balance: 242000.50,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'wallet-parent-ewallet',
    household_id: 'hh-101',
    owner_id: 'member-parent-2',
    name: 'GCash / Maya (Sarah)',
    wallet_type: 'e_wallet',
    is_shared: true,
    current_balance: 16200.00,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'wallet-teen-cash',
    household_id: 'hh-101',
    owner_id: 'member-teen-1',
    name: 'Alex Allowance & Cash',
    wallet_type: 'cash',
    is_shared: false,
    current_balance: 1450.00,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
];

export const initialCategories: Category[] = [
  {
    id: 'cat-internet',
    household_id: 'hh-101',
    name: 'Internet & Broadband Bills',
    icon_slug: 'wifi',
    monthly_budget_limit: 3500.00,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'cat-groceries',
    household_id: 'hh-101',
    name: 'Groceries & Household Supplies',
    icon_slug: 'shopping-cart',
    monthly_budget_limit: 25000.00,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'cat-utilities',
    household_id: 'hh-101',
    name: 'Utilities & Meralco Bills',
    icon_slug: 'zap',
    monthly_budget_limit: 8500.00,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'cat-school-kid-1',
    household_id: 'hh-101',
    name: 'School Dues & Tuition - Kid 1 (Alex)',
    icon_slug: 'graduation-cap',
    monthly_budget_limit: 12000.00,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'cat-school-kid-2',
    household_id: 'hh-101',
    name: 'School Dues & Tuition - Kid 2 (Chloe)',
    icon_slug: 'graduation-cap',
    monthly_budget_limit: 10000.00,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'cat-school-kid-3',
    household_id: 'hh-101',
    name: 'School Dues & Tuition - Kid 3 (Ethan)',
    icon_slug: 'graduation-cap',
    monthly_budget_limit: 8000.00,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'cat-dining',
    household_id: 'hh-101',
    name: 'Dining & Family Outings',
    icon_slug: 'utensils',
    monthly_budget_limit: 12000.00,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
];

const now = Date.now();
const hourAgo = new Date(now - 3 * 3600000).toISOString();
const yesterday = new Date(now - 48 * 3600000).toISOString();

export const initialTransactions: Transaction[] = [
  {
    id: 'tx-100',
    household_id: 'hh-101',
    wallet_id: 'wallet-bdo-credit-line',
    destination_wallet_id: null,
    category_id: 'cat-internet',
    payer_id: 'member-steve-admin',
    type: 'expense',
    amount: 1899.00,
    transaction_date: new Date(now - 1 * 86400000).toISOString().split('T')[0],
    note: 'PLDT Fiber Unli 200Mbps Monthly Internet Bill (Charged to Visa Credit Line)',
    receipt_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=400',
    created_at: hourAgo,
  },
  {
    id: 'tx-101',
    household_id: 'hh-101',
    wallet_id: 'wallet-main-bank',
    destination_wallet_id: null,
    category_id: 'cat-school-kid-1',
    payer_id: 'member-steve-admin',
    type: 'expense',
    amount: 12000.00,
    transaction_date: new Date(now - 6 * 3600000).toISOString().split('T')[0],
    note: 'Monthly Tuition & School Dues Payment - Kid 1 (Alex)',
    receipt_url: null,
    created_at: hourAgo,
  },
  {
    id: 'tx-102',
    household_id: 'hh-101',
    wallet_id: 'wallet-main-bank',
    destination_wallet_id: null,
    category_id: 'cat-school-kid-2',
    payer_id: 'member-parent-2',
    type: 'expense',
    amount: 10000.00,
    transaction_date: new Date(now - 12 * 3600000).toISOString().split('T')[0],
    note: 'Monthly Tuition & School Dues Payment - Kid 2 (Chloe)',
    receipt_url: null,
    created_at: hourAgo,
  },
  {
    id: 'tx-103',
    household_id: 'hh-101',
    wallet_id: 'wallet-bpi-credit-line',
    destination_wallet_id: null,
    category_id: 'cat-groceries',
    payer_id: 'member-parent-2',
    type: 'expense',
    amount: 3845.00,
    transaction_date: new Date(now - 24 * 3600000).toISOString().split('T')[0],
    note: 'Weekly Supermarket grocery haul (Credit Card)',
    receipt_url: null,
    created_at: yesterday,
  },
  {
    id: 'tx-104',
    household_id: 'hh-101',
    wallet_id: 'wallet-parent-ewallet',
    destination_wallet_id: 'wallet-teen-cash',
    category_id: null,
    payer_id: 'member-steve-admin',
    type: 'transfer',
    amount: 1000.00,
    transaction_date: new Date(now - 2 * 3600000).toISOString().split('T')[0],
    note: 'Weekly allowance GCash transfer to Alex',
    receipt_url: null,
    created_at: hourAgo,
  },
];

export const initialSavingsGoals: SavingsGoal[] = [
  {
    id: 'goal-tuition-kid-1',
    household_id: 'hh-101',
    name: 'Kid 1 (Alex) High School Semester Tuition Fund',
    target_amount: 60000.00,
    current_amount: 45000.00,
    target_date: '2026-08-15',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'goal-tuition-kid-2',
    household_id: 'hh-101',
    name: 'Kid 2 (Chloe) Middle School Tuition Fund',
    target_amount: 50000.00,
    current_amount: 35000.00,
    target_date: '2026-08-15',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'goal-tuition-kid-3',
    household_id: 'hh-101',
    name: 'Kid 3 (Ethan) Elementary Tuition & Books Fund',
    target_amount: 40000.00,
    current_amount: 28000.00,
    target_date: '2026-08-15',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'goal-emergency',
    household_id: 'hh-101',
    name: 'Household Emergency Sinking Fund',
    target_amount: 500000.00,
    current_amount: 425000.00,
    target_date: '2026-12-31',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
];

export const initialLoans: Loan[] = [
  {
    id: 'loan-tuition-installment',
    household_id: 'hh-101',
    name: 'Kid 1 High School Annual Tuition Amortization Plan',
    lender: 'St. Jude Academy Finance',
    total_principal: 120000.00,
    remaining_balance: 48000.00,
    interest_rate_annual: 0.0,
    monthly_amortization: 12000.00,
    due_day_of_month: 10,
    start_date: '2025-09-10',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'loan-housing',
    household_id: 'hh-101',
    name: 'BDO Housing Mortgage Loan',
    lender: 'BDO Unibank',
    total_principal: 2500000.00,
    remaining_balance: 1850000.00,
    interest_rate_annual: 6.5,
    monthly_amortization: 22500.00,
    due_day_of_month: 15,
    start_date: '2022-01-15',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'loan-car',
    household_id: 'hh-101',
    name: 'Toyota SUV Auto Financing',
    lender: 'Toyota Financial Services',
    total_principal: 950000.00,
    remaining_balance: 420000.00,
    interest_rate_annual: 7.2,
    monthly_amortization: 16800.00,
    due_day_of_month: 5,
    start_date: '2023-06-05',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
];

export const initialRecurringTransfers: RecurringTransfer[] = [
  {
    id: 'recurring-pldt-internet',
    household_id: 'hh-101',
    rule_type: 'expense',
    source_wallet_id: 'wallet-bdo-credit-line',
    destination_wallet_id: null,
    category_id: 'cat-internet',
    amount: 1899.00,
    frequency: 'monthly',
    next_run_date: new Date(Date.now() + 15 * 86400000).toISOString().split('T')[0],
    note: 'PLDT Fiber Unli 200Mbps Monthly Internet Bill',
    is_active: true,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'recurring-alex-allowance',
    household_id: 'hh-101',
    rule_type: 'transfer',
    source_wallet_id: 'wallet-parent-ewallet',
    destination_wallet_id: 'wallet-teen-cash',
    category_id: null,
    amount: 1000.00,
    frequency: 'weekly',
    next_run_date: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
    note: 'Automated Weekly Allowance to Alex (Kid 1)',
    is_active: true,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
];
